services:
  gateway:
    build: ./infra/nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
  frontend:
    image: socialite-frontend
    build:
      context: frontend
  backend:
    image: socialite-backend
    build:
      context: backend
