services:
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app:Z
      # Keep node_modules and build cache isolated inside the container
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  backend:
    build:
      target: build
    volumes:
      - ./backend:/src:Z
      # Keep binaries isolated inside the container
      - /src/bin
      - /src/obj
    command: dotnet watch run -v detailed --non-interactive --urls http://*:80
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
